image: gradle:6.8.3-jdk8

services:
  - "postgres:latest"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  SPRING_DATASOURCE_USER: postgres
  SPRING_DATASOURCE_PASSWORD: postgres

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test

test:
  stage: test
  script:
    - gradle :check
    - gradle :jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
